apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "periscope.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "periscope.name" . }}
    helm.sh/chart: {{ include "periscope.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "periscope.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        rollout-trigger: {{ randAlphaNum 10 | quote }}
      labels:
        app.kubernetes.io/name: {{ include "periscope.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "periscope.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: cache-volume
              mountPath: /app/.cache
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: {{ include "periscope.fullname" . }}-cache
      {{- end }}

